### ISSUE TITLE
Code missing for automation

### ISSUE THREAD

**Issue by dwardu89** [nagyrobi/home-assistant-configuration-examples#3]
I am trying to replicate this work for the Hive thermostat, however I am trying to find your automations 

`automation.heating_on_when_leave_home` which is not in the repository
`automation.heating_off_when_get_home` is also not there

are they created dynamically?

**Comment by Damazinho** [comment]
Same here...

**Comment by nagyrobi** [comment]
Since it's specific to each setup, it can't be included in this package.

Basically if you have some kind of presence detection system, you can make an automation in HA to switch the climate to away mode when nobody's at home and vice-versa.

It all depends on what integration you use to detect when is somebody at home or not.
